name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
    
  workflow_dispatch:
  
jobs:

  CI:
    runs-on: ubuntu:latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
           node-version: 16.13.2
           
      - name: Install mocka and other packages to tests
        run:
          cd src;
          npm install -g mocha;
          npm intall
          
      - name: Test execute
        run:
          mocha src/test/convert.js;
      

